name: Build and Test on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libgtest-dev

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure